name: Run Java Application

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '()'
        required: true
        default: 'master'
        type: string

# on:
#   schedule:
#     - cron: "*/5 * * * *"
#   workflow_dispatch:

jobs:
  run-jar:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v3

      - name: 设置 Java 环境
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 运行 Java 行动器
        run: java -jar githubActions.jar
