name: githubActions

# on:
#   schedule:
#     - cron: "*/5 * * * *"

jobs:
  run-jar:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v3

      - name: 设置 Java 环境
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: githubMonitor
        run: java -jar githubActions.jar --taskname=githubMonitor